### ISSUE TITLE
Use FileIO for IO?

### ISSUE THREAD

**Issue by Luapulu** [legend-exp/LegendTextIO.jl#1]
The most basic initial version of this would be to have all packages use [FileIO](https://github.com/JuliaIO/FileIO.jl) style `load` and `loadstreaming` functions. The more advanced version, once there's a registry for legend related julia packages: we can fork FileIO.jl here and add the relevant FileIO packages to the FileIO registry. That way, people working on legend can use the familiar FileIO syntax:

```julia
using FileIO
events = load("some-legend-file.ending")
```

This would also have the benefit, that we need not force multiple IO packages into one repo for easy of use reasons. Each file type can have its own repo and FileIO will deal with adding the releveant packages to the users environment, depending on the file type. This also means we don't need a seperate archive for test files, at least not for every file type. Since different IO packages can be separated easily, it's not a big deal to have one little test file checked into each repo. We may still have an archive for larger test files, but it wouldn't be needed for every file type.

If there's interest, I'd be happy to work on this.

**Comment by oschulz** [comment]
> we can fork FileIO.jl here and add the relevant FileIO packages to the FileIO registry. 

No, we certainly wouldn't want to maintain a fork of FileIO. It would also go against the principles of the Julia package and versioning system to use a project-specific modification of a registered packages, let alone use it long term.

For now, there's no harm in using custom load/save functions. We may harmonize them into a common `legend_load` and `legend_save` or so, long term. It should definitely be legend-specific function names (or some other LEGEND-specific dispatch path), since our load/save functions will be opinioned in the way the interpret file formats (LEGEND-style).

> This also means we don't need a seperate archive for test files, at least not for every file type.#

We definitely want to have a separate archive for test files: users who don't run tests shouldn't need to download the test data, also the test files will be shared with the LEGEND Python software stack. But we currently have only one repo for test data, and we'll keep it that way, it's perfectly acceptable for file-format-specific testing to download the whole set, since we'll take care to limit it's total size.

**Comment by Luapulu** [comment]
Yeah, makes sense. Wasn't a good idea. :)

**Comment by oschulz** [comment]
> Yeah, makes sense. Wasn't a good idea. :)

No worries, keep the ideas coming. :)
